[project]
name = "advent-of-code-2025"
version = "0.1.0"
description = "Advent of Code 2025!"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.4.0",
    "pandas>=2.3.3",
    "pytest>=9.0.2",
    "ruff>=0.14.10",
    "tqdm>=4.67.1",
    "ty>=0.0.8",
]
